// Code generated by Wire. DO NOT EDIT.

//go:generate go run github.com/google/wire/cmd/wire
//+build !wireinject

package wire

import (
	"dev/wire/internal/dao"
	"dev/wire/internal/server"
	"dev/wire/internal/service"
)

// Injectors from wire.go:

func InitializeServer(daos dao.Dao) (*server.Server, error) {
	serviceService := service.NewService(daos)
	serverServer := server.NewServer(serviceService)
	return serverServer, nil
}

func InitDB() (dao.Dao, error) {
	db, err := dao.NewDB()
	if err != nil {
		return nil, err
	}
	daoDao := dao.NewDao(db)
	return daoDao, nil
}
